"""initial schema

Revision ID: 9fae3bb0d29a
Revises: 
Create Date: 2025-10-22 20:10:41.715493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fae3bb0d29a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('imagem_url', sa.String(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categoria_id'), 'categoria', ['id'], unique=False)
    op.create_table('mesa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_mesa_id'), 'mesa', ['id'], unique=False)
    op.create_table('restaurantes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurantes_email'), 'restaurantes', ['email'], unique=True)
    op.create_index(op.f('ix_restaurantes_id'), 'restaurantes', ['id'], unique=False)
    op.create_table('chamadas_garcom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mesa_uuid', sa.String(length=36), nullable=False),
    sa.Column('motivo', sa.Integer(), nullable=False),
    sa.Column('detalhes', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atendido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atendido_por', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['mesa_uuid'], ['mesa.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chamadas_garcom_id'), 'chamadas_garcom', ['id'], unique=False)
    op.create_index(op.f('ix_chamadas_garcom_mesa_uuid'), 'chamadas_garcom', ['mesa_uuid'], unique=False)
    op.create_index('ix_chamadas_mesa_status', 'chamadas_garcom', ['mesa_uuid', 'status'], unique=False)
    op.create_index('ix_chamadas_status', 'chamadas_garcom', ['status'], unique=False)
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mesa_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimativa_entrega', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('observacoes_gerais', sa.String(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.CheckConstraint('status_id IN (1,2,3,4)', name='ck_pedido_status_id_range'),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('imagem_url', sa.String(), nullable=True),
    sa.Column('popular', sa.Boolean(), nullable=True),
    sa.Column('tempo_preparo_minutos', sa.Integer(), nullable=True),
    sa.Column('restricoes', sa.JSON(), nullable=True),
    sa.Column('adicionais', sa.JSON(), nullable=True),
    sa.Column('disponivel', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], name='fk_produto_categoria'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produto_id'), 'produto', ['id'], unique=False)
    op.create_table('item_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_pedido_id'), 'item_pedido', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_pedido_id'), table_name='item_pedido')
    op.drop_table('item_pedido')
    op.drop_index(op.f('ix_produto_id'), table_name='produto')
    op.drop_table('produto')
    op.drop_table('pedido')
    op.drop_index('ix_chamadas_status', table_name='chamadas_garcom')
    op.drop_index('ix_chamadas_mesa_status', table_name='chamadas_garcom')
    op.drop_index(op.f('ix_chamadas_garcom_mesa_uuid'), table_name='chamadas_garcom')
    op.drop_index(op.f('ix_chamadas_garcom_id'), table_name='chamadas_garcom')
    op.drop_table('chamadas_garcom')
    op.drop_index(op.f('ix_restaurantes_id'), table_name='restaurantes')
    op.drop_index(op.f('ix_restaurantes_email'), table_name='restaurantes')
    op.drop_table('restaurantes')
    op.drop_index(op.f('ix_mesa_id'), table_name='mesa')
    op.drop_table('mesa')
    op.drop_index(op.f('ix_categoria_id'), table_name='categoria')
    op.drop_table('categoria')
    # ### end Alembic commands ###
