services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: comandinha
      POSTGRES_PASSWORD: comandinha
      POSTGRES_DB: comandinha
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
